configuration:
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:xml-tasks:1.28.0"

flows:
  default:
    - expr: "${xmlUtils.mavenGav('pom.xml')}"
      out: gav

    - log: "groupId: ${gav.groupId}"
    - log: "artifactId: ${gav.artifactId}"
    - log: "version: ${gav.version}"
